# Generated by Django 4.2.30 on 2026-09-19 21:43

from django.db import migrations
from django.db.models import Count


def deduplicar_cuentas_corrientes_por_cliente(apps, schema_editor):
    """Antes de poder exigir `cliente` único (ver la migración siguiente, 0008), funde las
    cuentas corrientes duplicadas que ya puedan existir (alta duplicada desde el admin, sin nada
    que lo impidiera hasta ahora — ver venta.api VentaViewSet.imprimir, que rompía con
    MultipleObjectsReturned justamente por esto). Por cada cliente con más de una fila, conserva
    la que tenga más movimientos asociados (la que realmente se usó; empate -> la de id más
    chico, la más antigua) y le reasigna los movimientos de las demás antes de borrarlas, para no
    perder el historial de cobros ya registrado.

    Va en su propia migración, separada del AlterField que agrega el `unique` (0008): en Postgres
    el DELETE/UPDATE de acá deja triggers de foreign key pendientes sobre esta misma tabla, y un
    ALTER TABLE en la MISMA transacción los pisa con "cannot ALTER TABLE ... because it has
    pending trigger events" — 0007 y 0008 corren en transacciones separadas, así que para cuando
    0008 hace el ALTER TABLE ya no hay nada pendiente."""
    CuentaCorriente = apps.get_model('cuentacorriente', 'CuentaCorriente')
    MovimientoCuentaCorriente = apps.get_model('cuentacorriente', 'MovimientoCuentaCorriente')

    grupos_duplicados = (
        CuentaCorriente.objects.values('cliente_id')
        .annotate(cantidad=Count('id'))
        .filter(cantidad__gt=1)
    )
    for grupo in grupos_duplicados:
        cuentas = list(CuentaCorriente.objects.filter(cliente_id=grupo['cliente_id']).order_by('id'))
        canonica = max(
            cuentas,
            key=lambda c: (MovimientoCuentaCorriente.objects.filter(cuenta_id=c.id).count(), -c.id),
        )
        alguna_activa = any(c.activa for c in cuentas)
        for cuenta in cuentas:
            if cuenta.id == canonica.id:
                continue
            MovimientoCuentaCorriente.objects.filter(cuenta_id=cuenta.id).update(cuenta_id=canonica.id)
            cuenta.delete()
        if alguna_activa and not canonica.activa:
            canonica.activa = True
            canonica.save(update_fields=['activa'])


def no_reversible(apps, schema_editor):
    # Migración de datos (fusiona filas) — no hay forma de reconstruir las cuentas originales.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cuentacorriente", "0006_alter_movimientocuentacorriente_observaciones"),
    ]

    operations = [
        migrations.RunPython(deduplicar_cuentas_corrientes_por_cliente, no_reversible),
    ]
