# Generated by Django 4.2.30 on 2026-09-19 21:43

from django.db import migrations, models
from django.db.models import Count
import django.db.models.deletion


def deduplicar_cuentas_corrientes_por_cliente(apps, schema_editor):
    """Antes de poder exigir `cliente` único, funde las cuentas corrientes duplicadas que ya
    puedan existir (alta duplicada desde el admin, sin nada que lo impidiera hasta ahora — ver
    venta.api VentaViewSet.imprimir, que rompía con MultipleObjectsReturned justamente por esto).
    Por cada cliente con más de una fila, conserva la que tenga más movimientos asociados (la que
    realmente se usó; empate -> la de id más chico, la más antigua) y le reasigna los movimientos
    de las demás antes de borrarlas, para no perder el historial de cobros ya registrado."""
    CuentaCorriente = apps.get_model('cuentacorriente', 'CuentaCorriente')
    MovimientoCuentaCorriente = apps.get_model('cuentacorriente', 'MovimientoCuentaCorriente')

    grupos_duplicados = (
        CuentaCorriente.objects.values('cliente_id')
        .annotate(cantidad=Count('id'))
        .filter(cantidad__gt=1)
    )
    for grupo in grupos_duplicados:
        cuentas = list(CuentaCorriente.objects.filter(cliente_id=grupo['cliente_id']).order_by('id'))
        canonica = max(
            cuentas,
            key=lambda c: (MovimientoCuentaCorriente.objects.filter(cuenta_id=c.id).count(), -c.id),
        )
        alguna_activa = any(c.activa for c in cuentas)
        for cuenta in cuentas:
            if cuenta.id == canonica.id:
                continue
            MovimientoCuentaCorriente.objects.filter(cuenta_id=cuenta.id).update(cuenta_id=canonica.id)
            cuenta.delete()
        if alguna_activa and not canonica.activa:
            canonica.activa = True
            canonica.save(update_fields=['activa'])


def no_reversible(apps, schema_editor):
    # Migración de datos (fusiona filas) — no hay forma de reconstruir las cuentas originales.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0016_remove_cliente_fidelizado"),
        ("cuentacorriente", "0006_alter_movimientocuentacorriente_observaciones"),
    ]

    operations = [
        migrations.RunPython(deduplicar_cuentas_corrientes_por_cliente, no_reversible),
        migrations.AlterField(
            model_name="cuentacorriente",
            name="cliente",
            field=models.ForeignKey(
                error_messages={"unique": "El cliente ya tiene una cuenta corriente!"},
                on_delete=django.db.models.deletion.PROTECT,
                to="cliente.cliente",
                unique=True,
                verbose_name="Cliente",
            ),
        ),
    ]
