# Generated by Django 4.2.30 on 2026-09-19 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0016_remove_cliente_fidelizado"),
        ("cuentacorriente", "0007_deduplicar_cuentas_corrientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentacorriente",
            name="cliente",
            field=models.ForeignKey(
                error_messages={"unique": "El cliente ya tiene una cuenta corriente!"},
                on_delete=django.db.models.deletion.PROTECT,
                to="cliente.cliente",
                unique=True,
                verbose_name="Cliente",
            ),
        ),
    ]
