# Generated by Django 4.2.30 on 2026-09-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulo", "0026_remove_articulo_observaciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="abreviatura",
            field=models.CharField(
                help_text="Ejemplo: VACÍO ESP.",
                max_length=20,
                verbose_name="Abreviatura",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="nombre",
            field=models.CharField(
                help_text="Ejemplo: Vacío especial",
                max_length=60,
                unique=True,
                verbose_name="Nombre",
            ),
        ),
    ]
