# Generated by Django 4.2.30 on 2026-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulo", "0027_alter_articulo_abreviatura_alter_articulo_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="codigo",
            field=models.CharField(
                help_text="Ingrese el código de barras del artículo",
                max_length=10,
                verbose_name="Código de barras",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="nombre",
            field=models.CharField(
                help_text="Ejemplo: Vacío especial",
                max_length=60,
                verbose_name="Nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="articulo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("nombre",),
                name="articulo_nombre_activo_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="articulo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("codigo",),
                name="articulo_codigo_activo_unico",
            ),
        ),
    ]
