# Generated by Django 3.2.4 on 2026-02-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('empleado', '0016_merge_0015_auto_20220521_2126_0015_auto_20220526_1718'),
        ('articulo', '0026_remove_articulo_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('domicilio', models.CharField(max_length=100, unique=True, verbose_name='Domicilio')),
            ],
            options={
                'verbose_name': 'Deposito',
                'verbose_name_plural': 'Depositos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('destino_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('articulo', models.CharField(default='', max_length=100, verbose_name='Articulo')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(default='', max_length=50, verbose_name='Usuario')),
                ('observaciones', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Observaciones')),
                ('destino_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='contenttypes.contenttype')),
                ('origen_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Movimiento de articulo',
                'verbose_name_plural': 'Movimientos de articulos',
            },
        ),
        migrations.CreateModel(
            name='ArticuloSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Articulo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Articulo Sucursal',
                'verbose_name_plural': 'Articulos Sucursal',
            },
        ),
        migrations.CreateModel(
            name='ArticuloDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Articulo')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.deposito', verbose_name='Deposito')),
            ],
            options={
                'verbose_name': 'Articulo Deposito',
                'verbose_name_plural': 'Articulos Deposito',
            },
        ),
    ]
