# Generated by Django 3.2.4 on 2024-04-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0025_alter_venta_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventaarticulo',
            options={'ordering': ['-id'], 'verbose_name': 'Reporte Venta', 'verbose_name_plural': 'Ventas Articulos'},
        ),
    ]
