# Generated by Django 3.2.4 on 2024-04-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0027_alter_ventaarticulo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventaarticulo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Ventas Articulos'},
        ),
    ]
