# Generated by Django 4.2.30 on 2026-09-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0030_alter_ventaarticulo_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventaarticulo",
            name="nombre_articulo",
            field=models.CharField(max_length=60, verbose_name="Nombre de Articulo"),
        ),
    ]
