# Generated by Django 4.2.30 on 2026-10-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0031_alter_ventaarticulo_nombre_articulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventaarticulo",
            name="cantidad_peso",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
